// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivmuypzlemoxdctkwhqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2bXV5cHpsZW1veGRjdGt3aHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjU2NjUsImV4cCI6MjA3MTYwMTY2NX0.Mo_2i6IZi_m1kp3QIju0va4v-uVBws3eD1uA5dLndJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});